[openai]
API_KEY = "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"

[powerbi]
ACCESS_TOKEN = "aFu8Q~SR21mbA~b9k.TjVggAn3~XJj2xSAxbZcq4"
DATASET_ID = "5568335d-9053-4c8d-9f22-94840cfe4757"
